apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-api-config
data:
  MONGO_URI: "{{ .Values.env.MONGO_URI }}"
  REDIS_HOST: "{{ .Values.env.REDIS_HOST }}"
  REDIS_PORT: "{{ .Values.env.REDIS_PORT }}"
