ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "flask-api.local"  # Nome local definido no /etc/hosts
      paths:
        - path: /
          pathType: Prefix
  tls: []
